export const SUPPORTED_LANGUAGES = ['id', 'en'];

export const FILLER_WORDS = {
  id: ['eung', 'anu', 'uhm', 'eh', 'emm', 'hmm'],
  en: ['um', 'uh', 'like', 'you know', 'actually', 'basically', 'literally'],
};

export const TRANSLATIONS = {
  id: {
    // Navigation
    menu: 'Menu',
    history: 'Riwayat',
    dashboard: 'Dashboard',
    stats: 'Statistik',
    profile: 'Profil',
    settings: 'Pengaturan',
    voiceLab: 'Lab Suara',
    simulation: 'Simulasi',
    home: 'Beranda',
    back: 'Kembali',
    next: 'Selanjutnya',
    previous: 'Sebelumnya',
    skip: 'Lewati',
    done: 'Selesai',

    // Dashboard
    agent: 'Agent, Siap Latihan',
    systemTeks: 'Latih Katamu!',
    systemOffline: 'SISTEM OFFLINE',
    flightHours: 'Jam Terbang',
    averageScore: 'Skor Rata-rata',
    streak: 'Beruntun',
    quotaUsage: 'Penggunaan Kuota',
    dailyInsight: 'Wawasan Harian',
    achievementProgress: 'Progres Pencapaian',
    recentAchievements: 'Pencapaian Terbaru',
    noTrainingDataYet: 'Belum Ada Data Latihan',
    completeFirstSession: 'Selesaikan sesi latihan pertama Anda untuk melihat grafik progres di sini.',
    overallScoreTrend: 'Tren Skor Keseluruhan',
    vocalClarityTrend: 'Tren Kejelasan Vokal',
    latestSessionMetrics: 'Metrik Sesi Terakhir',
    performanceBreakdown: 'Rincian Performa',
    yourPerformance: 'Performa Anda',
    lastSessions: 'sesi terakhir',
    quickStats: 'Statistik Cepat',
    totalTime: 'Total Waktu',
    sessions: 'Sesi',

    // History
    trainingHistory: 'Riwayat Latihan',
    sessionsFound: 'sesi ditemukan',
    noMatchingSessions: 'Tidak Ada Sesi yang Cocok',
    noTrainingSessionsYet: 'Belum Ada Sesi Latihan',
    adjustFilters: 'Coba sesuaikan filter pencarian untuk menemukan lebih banyak sesi.',
    startFirstSession: 'Mulai sesi latihan pertama Anda untuk melihat progres di sini.',
    clearFilters: 'Hapus Filter',
    startTraining: 'Mulai Latihan',
    somethingWentWrong: 'Terjadi Kesalahan',
    failedToLoadHistory: 'Gagal memuat riwayat sesi',
    tryAgain: 'Coba Lagi',
    searchSessions: 'Cari sesi...',
    filterByCategory: 'Filter berdasarkan kategori',
    filterByDate: 'Filter berdasarkan tanggal',
    allCategories: 'Semua Kategori',
    allTime: 'Semua Waktu',
    today: 'Hari Ini',
    thisWeek: 'Minggu Ini',
    thisMonth: 'Bulan Ini',
    lastMonth: 'Bulan Lalu',
    customRange: 'Rentang Kustom',
    noResults: 'Tidak ada hasil',
    retry: 'Coba Lagi',
    viewDetails: 'Lihat Detail',
    viewReport: 'Lihat Laporan',

    // Voice Lab
    voiceSlots: 'Slot Suara',
    clonedVoices: 'suara kloning',
    cloneVoice: 'Kloning Suara',
    systemVoices: 'SUARA SISTEM',
    yourClonedVoices: 'SUARA KLONING ANDA',
    systemVoice: 'Suara Sistem',
    clonedVoice: 'Suara Kloning',
    ttsPlayground: 'TTS Playground',
    testVoicesDescription: 'Uji suara Anda dengan teks kustom. Pilih suara dan ketik pesan untuk mendengarnya.',
    voiceSettings: 'Pengaturan Suara',
    stability: 'Stabilitas',
    similarity: 'Kemiripan',
    stabilityDescription: 'Stabilitas lebih tinggi = lebih konsisten, lebih rendah = lebih ekspresif',
    similarityDescription: 'Kemiripan lebih tinggi = lebih dekat dengan suara asli',
    manageVoiceLibrary: 'Kelola pustaka suara dan kloning suara baru',
    slotLimitReached: 'Batas Slot Tercapai',
    slotLimitMessage: 'Anda hanya dapat memiliki 5 suara kloning. Hapus suara yang ada untuk menambahkan yang baru.',
    cannotDeleteSystem: 'Suara sistem tidak dapat dihapus.',
    deleteVoiceConfirm: 'Apakah Anda yakin ingin menghapus',
    voiceDeleted: 'Suara berhasil dihapus',
    voiceSaved: 'Pengaturan suara disimpan',
    uploadAudioSample: 'Unggah sampel audio',
    recordVoice: 'Rekam Suara',
    selectVoice: 'Pilih Suara',
    previewVoice: 'Pratinjau Suara',
    playing: 'Memutar...',

    // Settings
    appearance: 'Tampilan',
    theme: 'Tema',
    language: 'Bahasa',
    light: 'Terang',
    dark: 'Gelap',
    system: 'Sistem',
    indonesian: 'Bahasa Indonesia',
    english: 'Bahasa Inggris',
    darkMode: 'Mode Gelap',
    lightMode: 'Mode Terang',
    cyberProfessionalDark: 'Tema gelap cyber-profesional',
    cleanLightTheme: 'Tema terang yang bersih',
    apiConfiguration: 'Konfigurasi API',
    elevenLabsApiKey: 'Kunci API ElevenLabs',
    geminiApiKey: 'Kunci API Gemini',
    notConfigured: 'Belum dikonfigurasi',
    keysConfigured: 'Kunci sudah dikonfigurasi',
    tapToAddKeys: 'Ketuk untuk menambahkan kunci API Anda',
    apiKeysSecure: 'Kunci API Anda disimpan dengan aman di perangkat menggunakan penyimpanan terenkripsi.',
    validateKeys: 'Validasi Kunci',
    saveKeys: 'Simpan Kunci',
    validating: 'Memvalidasi...',
    valid: 'Valid',
    invalid: 'Tidak Valid',
    enterGeminiKey: 'Masukkan kunci API Gemini',
    enterElevenLabsKey: 'Masukkan kunci API ElevenLabs',
    dailySpendingLimit: 'Batas Pengeluaran Harian',
    currentUsage: 'Penggunaan Saat Ini',
    daily: 'Harian',
    monthly: 'Bulanan',
    perDay: 'per hari',
    audioSettings: 'Pengaturan Audio',
    audioFeedback: 'AUDIO & UMPAN BALIK',
    vadSensitivity: 'Sensitivitas VAD',
    vadLow: 'Rendah (Noise Floor + 20dB)',
    vadMedium: 'Sedang (Noise Floor + 12dB)',
    vadHigh: 'Tinggi (Noise Floor + 5dB)',
    vadLowDesc: 'Noise Floor + 20dB - Kurang sensitif',
    vadMediumDesc: 'Noise Floor + 12dB - Seimbang',
    vadHighDesc: 'Noise Floor + 5dB - Lebih sensitif',
    inputDevice: 'Perangkat Input',
    outputDevice: 'Perangkat Output',
    systemSettings: 'Pengaturan Sistem',
    hapticFeedback: 'Umpan Balik Haptic',
    hapticDescription: 'Getaran saat interupsi barge-in',
    mockMode: 'Mode Mock',
    mockModeDesc: 'Jalankan tanpa panggilan API nyata',
    debugLogs: 'Log Debug',
    debugLogsDesc: 'Aktifkan logging verbose untuk debugging',
    dataManagement: 'MANAJEMEN DATA',
    exportData: 'Ekspor Data',
    clearSessionData: 'Hapus Data Sesi',
    storageInfo: 'Info Penyimpanan',
    resetQuota: 'Reset Kuota',
    clearAllData: 'Hapus Semua Data',
    deleteSessionsDocsVoices: 'Hapus sesi, dokumen, dan suara',
    apiSecurity: 'API & KEAMANAN',
    apiKeys: 'Kunci API',
    dailyBudget: 'Anggaran Harian',
    aboutResonance: 'Tentang Resonance',
    version: 'Versi',
    clearAllDataWarning: 'Ini akan menghapus semua sesi, dokumen, dan aset suara. Tindakan ini tidak dapat dibatalkan.',
    clear: 'Hapus',
    allDataCleared: 'Semua data telah dihapus.',
    resetQuotaConfirm: 'Ini akan mereset pelacakan penggunaan kuota harian dan bulanan Anda. Lanjutkan?',
    reset: 'Reset',
    quotaReset: 'Penggunaan kuota telah direset',
    budgetAmount: 'Jumlah (USD)',
    setBudgetDesc: 'Tetapkan batas pengeluaran harian untuk penggunaan API. Anda akan diperingatkan saat mendekati batas ini.',
    budgetSet: 'Anggaran harian ditetapkan ke',
    invalidAmount: 'Jumlah Tidak Valid',
    enterValidBudget: 'Masukkan jumlah anggaran yang valid lebih dari 0',
    docs: 'dok',
    used: 'digunakan',

    // Export and Reports
    sessionReport: 'Laporan Sesi',
    sessionInfo: 'Informasi Sesi',
    sessionId: 'ID Sesi',
    date: 'Tanggal',
    scenario: 'Skenario',
    mode: 'Mode',
    duration: 'Durasi',
    metrics: 'Metrik',
    score: 'Skor',
    pace: 'Kecepatan',
    fillerWords: 'Kata Pengisi',
    clarity: 'Kejelasan',
    confidence: 'Kepercayaan Diri',
    transcript: 'Transkrip',
    exportPDF: 'Ekspor PDF',
    exportCSV: 'Ekspor CSV',
    shareReport: 'Bagikan Laporan',
    downloadReport: 'Unduh Laporan',
    coachFeedback: 'Umpan Balik Pelatih',
    positiveAspects: 'Aspek Positif',
    improvementAreas: 'Area Perbaikan',
    nextSteps: 'Langkah Selanjutnya',
    overallSummary: 'Ringkasan Keseluruhan',
    emotionalTelemetry: 'Telemetri Emosional',
    wpm: 'KPM',
    wordsPerMinute: 'Kata per Menit',
    minutes: 'menit',
    seconds: 'detik',
    hours: 'jam',

    // Session Setup
    sessionSetup: 'Pengaturan Sesi',
    selectScenario: 'Pilih Skenario',
    selectLanguage: 'Pilih Bahasa',
    chaosEngine: 'Chaos Engine',
    chaosEngineDesc: 'Aktifkan gangguan dunia nyata',
    randomVoiceGen: 'Generasi Suara Acak',
    randomVoiceDesc: 'Variasi pitch dan kecepatan',
    backgroundNoise: 'Kebisingan Latar',
    backgroundNoiseDesc: 'Suara kantor, hujan, lalu lintas, kafe',
    hardwareFailure: 'Kegagalan Perangkat Keras',
    hardwareFailureDesc: 'Simulasi mic mute, koneksi terputus',
    contextFiles: 'File Konteks',
    uploadDocument: 'Unggah Dokumen',
    uploadPdfDocx: 'Unggah PDF/DOCX untuk konteks skenario',
    noFilesUploaded: 'Belum ada file yang diunggah',
    removeFile: 'Hapus File',
    startSimulation: 'Mulai Simulasi',
    preparing: 'Mempersiapkan...',

    // Scenarios - Sales & Negotiation
    crisisnegotiation: 'Negosiasi Krisis',
    salesobjection: 'Penanganan Keberatan Penjualan',
    pricenegotiation: 'Negosiasi Harga',
    contractnegotiation: 'Negosiasi Kontrak',
    closingdeal: 'Menutup Kesepakatan',
    
    // Scenarios - Customer Service
    customercomplaint: 'Keluhan Pelanggan',
    refundrequest: 'Permintaan Pengembalian Dana',
    technicalsupport: 'Dukungan Teknis',
    servicerecovery: 'Pemulihan Layanan',
    escalationhandling: 'Penanganan Eskalasi',
    
    // Scenarios - Management & HR
    performancereview: 'Tinjauan Kinerja',
    difficultconversation: 'Percakapan Sulit',
    terminationmeeting: 'Rapat Pemutusan Hubungan Kerja',
    salarynegotiation: 'Negosiasi Gaji',
    conflictresolution: 'Resolusi Konflik',
    
    // Scenarios - Presentations & Meetings
    presentationqa: 'Tanya Jawab Presentasi',
    investorpitch: 'Presentasi Investor',
    boardmeeting: 'Rapat Dewan',
    teambriefing: 'Briefing Tim',
    
    // Scenarios - Other
    jobinterview: 'Wawancara Kerja',
    mediainterview: 'Wawancara Media',
    coldcalling: 'Cold Calling',
    debtcollection: 'Penagihan Utang',
    insuranceclaim: 'Klaim Asuransi',

    // Active Session
    activeSession: 'Sesi Aktif',
    listening: 'Mendengarkan...',
    speaking: 'Berbicara...',
    processing: 'Memproses...',
    tapToSpeak: 'Ketuk untuk berbicara',
    holdToSpeak: 'Tahan untuk berbicara',
    releaseToSend: 'Lepas untuk mengirim',
    endCall: 'Akhiri Panggilan',
    muteAudio: 'Bisukan Audio',
    unmuteAudio: 'Bunyikan Audio',
    callerInfo: 'Info Penelepon',
    callDuration: 'Durasi Panggilan',
    currentScore: 'Skor Saat Ini',
    bargeInDetected: 'Barge-in Terdeteksi!',

    // Stress Mode
    stressModeTitle: 'Mode Stres',
    callerQueue: 'Antrian Penelepon',
    waitingCallers: 'Penelepon Menunggu',
    staminaBar: 'Bar Stamina',
    nextCaller: 'Penelepon Berikutnya',
    skipCaller: 'Lewati Penelepon',
    takeBreak: 'Istirahat',
    queueLength: 'Panjang Antrian',
    interCallDelay: 'Jeda Antar Panggilan',

    // Common
    comingSoon: 'Segera hadir...',
    loading: 'Memuat...',
    loadingSettings: 'Memuat pengaturan...',
    error: 'Kesalahan',
    success: 'Berhasil',
    cancel: 'Batal',
    confirm: 'Konfirmasi',
    save: 'Simpan',
    delete: 'Hapus',
    edit: 'Edit',
    points: 'poin',
    close: 'Tutup',
    ok: 'OK',
    yes: 'Ya',
    no: 'Tidak',
    on: 'Aktif',
    off: 'Nonaktif',
    enabled: 'Diaktifkan',
    disabled: 'Dinonaktifkan',
    select: 'Pilih',
    selected: 'Dipilih',
    search: 'Cari',
    filter: 'Filter',
    sort: 'Urutkan',
    refresh: 'Segarkan',
    more: 'Lebih',
    less: 'Kurang',
    all: 'Semua',
    none: 'Tidak Ada',
    default: 'Default',
    custom: 'Kustom',
    auto: 'Otomatis',
    manual: 'Manual',
    online: 'Online',
    offline: 'Offline',
    connected: 'Terhubung',
    disconnected: 'Terputus',
    connecting: 'Menghubungkan...',
    reconnecting: 'Menghubungkan ulang...',
    failed: 'Gagal',
    completed: 'Selesai',
    inProgress: 'Sedang Berlangsung',
    pending: 'Tertunda',
    active: 'Aktif',
    inactive: 'Tidak Aktif',
    new: 'Baru',
    updated: 'Diperbarui',
    created: 'Dibuat',
    modified: 'Dimodifikasi',
    deleted: 'Dihapus',
    copied: 'Disalin',
    shared: 'Dibagikan',
    downloaded: 'Diunduh',
    uploaded: 'Diunggah',
    saved: 'Disimpan',
    sent: 'Terkirim',
    received: 'Diterima',
    required: 'Wajib',
    optional: 'Opsional',
    recommended: 'Direkomendasikan',
    warning: 'Peringatan',
    info: 'Info',
    tip: 'Tips',
    note: 'Catatan',
    help: 'Bantuan',
    support: 'Dukungan',
    feedback: 'Umpan Balik',
    about: 'Tentang',
    privacy: 'Privasi',
    terms: 'Ketentuan',
    license: 'Lisensi',

    // Session
    startSession: 'Mulai Sesi',
    endSession: 'Akhiri Sesi',
    pauseSession: 'Jeda Sesi',
    resumeSession: 'Lanjutkan Sesi',
    standardTraining: 'Latihan Standar',
    stressMode: 'Mode Stres',
    practiceWithAI: 'Berlatih dengan percakapan bertenaga AI',
    handleMultipleCallers: 'Tangani beberapa penelepon di bawah tekanan',
    chooseTrainingMode: 'Pilih mode latihan Anda',
    sessionCompleted: 'Sesi Selesai',
    sessionPaused: 'Sesi Dijeda',
    sessionResumed: 'Sesi Dilanjutkan',
    sessionCancelled: 'Sesi Dibatalkan',

    // Splash & Onboarding
    initializingAudio: 'Menginisialisasi mesin audio...',
    settingUpVoice: 'Menyiapkan deteksi suara...',
    calibratingMic: 'Mengkalibrasi mikrofon...',
    finalizingSetup: 'Menyelesaikan pengaturan...',
    ready: 'Siap!',
    welcome: 'Selamat Datang',
    welcomeToResonance: 'Selamat Datang di Resonance',
    getStarted: 'Mulai',
    continueSetup: 'Lanjutkan Pengaturan',

    // Achievements
    achievement: 'Pencapaian',
    achievements: 'Pencapaian',
    unlocked: 'Terbuka',
    locked: 'Terkunci',
    progress: 'Progres',
    newAchievement: 'Pencapaian Baru!',
    congratulations: 'Selamat!',
    keepGoing: 'Terus Semangat!',
  },


  en: {
    // Navigation
    menu: 'Menu',
    history: 'History',
    dashboard: 'Dashboard',
    stats: 'Stats',
    profile: 'Profile',
    settings: 'Settings',
    voiceLab: 'Voice Lab',
    simulation: 'Simulation',
    home: 'Home',
    back: 'Back',
    next: 'Next',
    previous: 'Previous',
    skip: 'Skip',
    done: 'Done',

    // Dashboard
    agent: 'Agent,Ready For Training',
    systemTeks: 'Train Your word!',
    systemOffline: 'SYSTEM OFFLINE',
    flightHours: 'Flight Hours',
    averageScore: 'Average Score',
    streak: 'Streak',
    quotaUsage: 'Quota Usage',
    dailyInsight: 'Daily Insight',
    achievementProgress: 'Achievement Progress',
    recentAchievements: 'Recent Achievements',
    noTrainingDataYet: 'No Training Data Yet',
    completeFirstSession: 'Complete your first training session to see your progress charts here.',
    overallScoreTrend: 'Overall Score Trend',
    vocalClarityTrend: 'Vocal Clarity Trend',
    latestSessionMetrics: 'Latest Session Metrics',
    performanceBreakdown: 'Performance breakdown',
    yourPerformance: 'Your Performance',
    lastSessions: 'last sessions',
    quickStats: 'Quick Stats',
    totalTime: 'Total Time',
    sessions: 'Sessions',

    // History
    trainingHistory: 'Training History',
    sessionsFound: 'sessions found',
    noMatchingSessions: 'No Matching Sessions',
    noTrainingSessionsYet: 'No Training Sessions Yet',
    adjustFilters: 'Try adjusting your search filters to find more sessions.',
    startFirstSession: 'Start your first training session to see your progress here.',
    clearFilters: 'Clear Filters',
    startTraining: 'Start Training',
    somethingWentWrong: 'Something Went Wrong',
    failedToLoadHistory: 'Failed to load session history',
    tryAgain: 'Try Again',
    searchSessions: 'Search sessions...',
    filterByCategory: 'Filter by category',
    filterByDate: 'Filter by date',
    allCategories: 'All Categories',
    allTime: 'All Time',
    today: 'Today',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    lastMonth: 'Last Month',
    customRange: 'Custom Range',
    noResults: 'No results',
    retry: 'Retry',
    viewDetails: 'View Details',
    viewReport: 'View Report',

    // Voice Lab
    voiceSlots: 'Voice Slots',
    clonedVoices: 'cloned voices',
    cloneVoice: 'Clone Voice',
    systemVoices: 'SYSTEM VOICES',
    yourClonedVoices: 'YOUR CLONED VOICES',
    systemVoice: 'System Voice',
    clonedVoice: 'Cloned Voice',
    ttsPlayground: 'TTS Playground',
    testVoicesDescription: 'Test your voices with custom text. Select a voice and type your message to hear it spoken.',
    voiceSettings: 'Voice Settings',
    stability: 'Stability',
    similarity: 'Similarity',
    stabilityDescription: 'Higher stability = more consistent, lower = more expressive',
    similarityDescription: 'Higher similarity = closer to original voice',
    manageVoiceLibrary: 'Manage your voice library and clone new voices',
    slotLimitReached: 'Slot Limit Reached',
    slotLimitMessage: 'You can only have 5 cloned voices. Delete an existing voice to add a new one.',
    cannotDeleteSystem: 'System voices cannot be deleted.',
    deleteVoiceConfirm: 'Are you sure you want to delete',
    voiceDeleted: 'Voice deleted successfully',
    voiceSaved: 'Voice settings saved',
    uploadAudioSample: 'Upload audio sample',
    recordVoice: 'Record Voice',
    selectVoice: 'Select Voice',
    previewVoice: 'Preview Voice',
    playing: 'Playing...',

    // Settings
    appearance: 'Appearance',
    theme: 'Theme',
    language: 'Language',
    light: 'Light',
    dark: 'Dark',
    system: 'System',
    indonesian: 'Indonesian',
    english: 'English',
    darkMode: 'Dark Mode',
    lightMode: 'Light Mode',
    cyberProfessionalDark: 'Cyber-professional dark theme',
    cleanLightTheme: 'Clean light theme',
    apiConfiguration: 'API Configuration',
    elevenLabsApiKey: 'ElevenLabs API Key',
    geminiApiKey: 'Gemini API Key',
    notConfigured: 'Not configured',
    keysConfigured: 'Keys configured',
    tapToAddKeys: 'Tap to add your API keys',
    apiKeysSecure: 'Your API keys are stored securely on your device using encrypted storage.',
    validateKeys: 'Validate Keys',
    saveKeys: 'Save Keys',
    validating: 'Validating...',
    valid: 'Valid',
    invalid: 'Invalid',
    enterGeminiKey: 'Enter Gemini API key',
    enterElevenLabsKey: 'Enter ElevenLabs API key',
    dailySpendingLimit: 'Daily Spending Limit',
    currentUsage: 'Current Usage',
    daily: 'Daily',
    monthly: 'Monthly',
    perDay: 'per day',
    audioSettings: 'Audio Settings',
    audioFeedback: 'AUDIO & FEEDBACK',
    vadSensitivity: 'VAD Sensitivity',
    vadLow: 'Low (Noise Floor + 20dB)',
    vadMedium: 'Medium (Noise Floor + 12dB)',
    vadHigh: 'High (Noise Floor + 5dB)',
    vadLowDesc: 'Noise Floor + 20dB - Less sensitive',
    vadMediumDesc: 'Noise Floor + 12dB - Balanced',
    vadHighDesc: 'Noise Floor + 5dB - More sensitive',
    inputDevice: 'Input Device',
    outputDevice: 'Output Device',
    systemSettings: 'System Settings',
    hapticFeedback: 'Haptic Feedback',
    hapticDescription: 'Vibration on barge-in interruption',
    mockMode: 'Mock Mode',
    mockModeDesc: 'Run without real API calls',
    debugLogs: 'Debug Logs',
    debugLogsDesc: 'Enable verbose logging for debugging',
    dataManagement: 'DATA MANAGEMENT',
    exportData: 'Export Data',
    clearSessionData: 'Clear Session Data',
    storageInfo: 'Storage Info',
    resetQuota: 'Reset Quota',
    clearAllData: 'Clear All Data',
    deleteSessionsDocsVoices: 'Delete sessions, documents, and voices',
    apiSecurity: 'API & SECURITY',
    apiKeys: 'API Keys',
    dailyBudget: 'Daily Budget',
    aboutResonance: 'About Resonance',
    version: 'Version',
    clearAllDataWarning: 'This will delete all sessions, documents, and voice assets. This action cannot be undone.',
    clear: 'Clear',
    allDataCleared: 'All data has been cleared.',
    resetQuotaConfirm: 'This will reset your daily and monthly quota usage tracking. Continue?',
    reset: 'Reset',
    quotaReset: 'Quota usage has been reset',
    budgetAmount: 'Amount (USD)',
    setBudgetDesc: 'Set your daily spending limit for API usage. You\'ll be warned when approaching this limit.',
    budgetSet: 'Daily budget set to',
    invalidAmount: 'Invalid Amount',
    enterValidBudget: 'Please enter a valid budget amount greater than 0',
    docs: 'docs',
    used: 'used',

    // Export and Reports
    sessionReport: 'Session Report',
    sessionInfo: 'Session Information',
    sessionId: 'Session ID',
    date: 'Date',
    scenario: 'Scenario',
    mode: 'Mode',
    duration: 'Duration',
    metrics: 'Performance Metrics',
    score: 'Score',
    pace: 'Pace',
    fillerWords: 'Filler Words',
    clarity: 'Clarity',
    confidence: 'Confidence',
    transcript: 'Transcript',
    exportPDF: 'Export PDF',
    exportCSV: 'Export CSV',
    shareReport: 'Share Report',
    downloadReport: 'Download Report',
    coachFeedback: 'Coach Feedback',
    positiveAspects: 'Positive Aspects',
    improvementAreas: 'Improvement Areas',
    nextSteps: 'Next Steps',
    overallSummary: 'Overall Summary',
    emotionalTelemetry: 'Emotional Telemetry',
    wpm: 'WPM',
    wordsPerMinute: 'Words per Minute',
    minutes: 'minutes',
    seconds: 'seconds',
    hours: 'hours',

    // Session Setup
    sessionSetup: 'Session Setup',
    selectScenario: 'Select Scenario',
    selectLanguage: 'Select Language',
    chaosEngine: 'Chaos Engine',
    chaosEngineDesc: 'Enable real-world disruptions',
    randomVoiceGen: 'Random Voice Gen',
    randomVoiceDesc: 'Pitch and speed variations',
    backgroundNoise: 'Background Noise',
    backgroundNoiseDesc: 'Office, rain, traffic, cafe sounds',
    hardwareFailure: 'Hardware Failure',
    hardwareFailureDesc: 'Simulate mic mute, connection drops',
    contextFiles: 'Context Files',
    uploadDocument: 'Upload Document',
    uploadPdfDocx: 'Upload PDF/DOCX for scenario context',
    noFilesUploaded: 'No files uploaded yet',
    removeFile: 'Remove File',
    startSimulation: 'Start Simulation',
    preparing: 'Preparing...',

    // Scenarios - Sales & Negotiation
    crisisnegotiation: 'Crisis Negotiation',
    salesobjection: 'Sales Objection Handling',
    pricenegotiation: 'Price Negotiation',
    contractnegotiation: 'Contract Negotiation',
    closingdeal: 'Closing Deal',
    
    // Scenarios - Customer Service
    customercomplaint: 'Customer Complaint',
    refundrequest: 'Refund Request',
    technicalsupport: 'Technical Support',
    servicerecovery: 'Service Recovery',
    escalationhandling: 'Escalation Handling',
    
    // Scenarios - Management & HR
    performancereview: 'Performance Review',
    difficultconversation: 'Difficult Conversation',
    terminationmeeting: 'Termination Meeting',
    salarynegotiation: 'Salary Negotiation',
    conflictresolution: 'Conflict Resolution',
    
    // Scenarios - Presentations & Meetings
    presentationqa: 'Presentation Q&A',
    investorpitch: 'Investor Pitch',
    boardmeeting: 'Board Meeting',
    teambriefing: 'Team Briefing',
    
    // Scenarios - Other
    jobinterview: 'Job Interview',
    mediainterview: 'Media Interview',
    coldcalling: 'Cold Calling',
    debtcollection: 'Debt Collection',
    insuranceclaim: 'Insurance Claim',

    // Active Session
    activeSession: 'Active Session',
    listening: 'Listening...',
    speaking: 'Speaking...',
    processing: 'Processing...',
    tapToSpeak: 'Tap to speak',
    holdToSpeak: 'Hold to speak',
    releaseToSend: 'Release to send',
    endCall: 'End Call',
    muteAudio: 'Mute Audio',
    unmuteAudio: 'Unmute Audio',
    callerInfo: 'Caller Info',
    callDuration: 'Call Duration',
    currentScore: 'Current Score',
    bargeInDetected: 'Barge-in Detected!',

    // Stress Mode
    stressModeTitle: 'Stress Mode',
    callerQueue: 'Caller Queue',
    waitingCallers: 'Waiting Callers',
    staminaBar: 'Stamina Bar',
    nextCaller: 'Next Caller',
    skipCaller: 'Skip Caller',
    takeBreak: 'Take Break',
    queueLength: 'Queue Length',
    interCallDelay: 'Inter-call Delay',

    // Common
    comingSoon: 'Coming soon...',
    loading: 'Loading...',
    loadingSettings: 'Loading settings...',
    error: 'Error',
    success: 'Success',
    cancel: 'Cancel',
    confirm: 'Confirm',
    save: 'Save',
    delete: 'Delete',
    edit: 'Edit',
    points: 'points',
    close: 'Close',
    ok: 'OK',
    yes: 'Yes',
    no: 'No',
    on: 'On',
    off: 'Off',
    enabled: 'Enabled',
    disabled: 'Disabled',
    select: 'Select',
    selected: 'Selected',
    search: 'Search',
    filter: 'Filter',
    sort: 'Sort',
    refresh: 'Refresh',
    more: 'More',
    less: 'Less',
    all: 'All',
    none: 'None',
    default: 'Default',
    custom: 'Custom',
    auto: 'Auto',
    manual: 'Manual',
    online: 'Online',
    offline: 'Offline',
    connected: 'Connected',
    disconnected: 'Disconnected',
    connecting: 'Connecting...',
    reconnecting: 'Reconnecting...',
    failed: 'Failed',
    completed: 'Completed',
    inProgress: 'In Progress',
    pending: 'Pending',
    active: 'Active',
    inactive: 'Inactive',
    new: 'New',
    updated: 'Updated',
    created: 'Created',
    modified: 'Modified',
    deleted: 'Deleted',
    copied: 'Copied',
    shared: 'Shared',
    downloaded: 'Downloaded',
    uploaded: 'Uploaded',
    saved: 'Saved',
    sent: 'Sent',
    received: 'Received',
    required: 'Required',
    optional: 'Optional',
    recommended: 'Recommended',
    warning: 'Warning',
    info: 'Info',
    tip: 'Tip',
    note: 'Note',
    help: 'Help',
    support: 'Support',
    feedback: 'Feedback',
    about: 'About',
    privacy: 'Privacy',
    terms: 'Terms',
    license: 'License',

    // Session
    startSession: 'Start Session',
    endSession: 'End Session',
    pauseSession: 'Pause Session',
    resumeSession: 'Resume Session',
    standardTraining: 'Standard Training',
    stressMode: 'Stress Mode',
    practiceWithAI: 'Practice with AI-powered conversations',
    handleMultipleCallers: 'Handle multiple callers under pressure',
    chooseTrainingMode: 'Choose your training mode',
    sessionCompleted: 'Session Completed',
    sessionPaused: 'Session Paused',
    sessionResumed: 'Session Resumed',
    sessionCancelled: 'Session Cancelled',

    // Splash & Onboarding
    initializingAudio: 'Initializing audio engine...',
    settingUpVoice: 'Setting up voice detection...',
    calibratingMic: 'Calibrating microphone...',
    finalizingSetup: 'Finalizing setup...',
    ready: 'Ready!',
    welcome: 'Welcome',
    welcomeToResonance: 'Welcome to Resonance',
    getStarted: 'Get Started',
    continueSetup: 'Continue Setup',

    // Achievements
    achievement: 'Achievement',
    achievements: 'Achievements',
    unlocked: 'Unlocked',
    locked: 'Locked',
    progress: 'Progress',
    newAchievement: 'New Achievement!',
    congratulations: 'Congratulations!',
    keepGoing: 'Keep Going!',
  },
};

// Additional translation keys for onboarding and other screens
export const ADDITIONAL_TRANSLATIONS = {
  id: {
    // Onboarding
    masterYourVoice: 'Kuasai Suara Anda',
    highStakesTraining: 'Pelatihan Komunikasi Berisiko Tinggi',
    trainForCritical: 'Latih percakapan kritis dengan simulasi bertenaga AI yang menyesuaikan dengan performa Anda.',
    ultraLowLatency: 'Latensi Ultra Rendah',
    naturalConversation: 'Alur Percakapan Alami',
    experienceRealistic: 'Rasakan interaksi realistis dengan deteksi aktivitas suara dan kemampuan interupsi alami.',
    realWorldDisruptions: 'Gangguan Dunia Nyata',
    practiceHandling: 'Latih menangani tantangan tak terduga dengan kebisingan latar, variasi suara, dan kegagalan perangkat keras.',
    offlineFirst: 'Offline-First',
    trainAnywhere: 'Latihan Kapan Saja, Di Mana Saja',
    fullFunctionality: 'Fungsionalitas penuh tanpa ketergantungan internet. Progres Anda tetap privat dan aman di perangkat.',
    
    // Report
    fillerWordTip: 'Kata pengisi terdeteksi. Coba berhenti sejenak untuk mengumpulkan pikiran.',
    positiveAspectsDesc: 'Mempertahankan nada profesional sepanjang percakapan.',
    improvementAreasDesc: 'Kurangi kata pengisi untuk meningkatkan kejelasan.',
    nextStepsDesc: 'Latih berhenti sejenak daripada menggunakan kata pengisi.',
    grade: 'Nilai',
    notRecorded: 'Tidak tercatat',
    
    // Session
    retrySession: 'Ulangi Sesi Ini',
    sessionStatus: 'Status Sesi',
    completionStatus: 'Status Penyelesaian',
    
    // Quota
    quotaExceeded: 'Kuota Terlampaui',
    criticalUsage: 'Penggunaan Kritis',
    highUsage: 'Penggunaan Tinggi',
    normalUsage: 'Penggunaan Normal',
    remainingToday: 'Sisa Hari Ini',
    usageTrend: 'Tren Penggunaan 7 Hari (%)',
    
    // Session Setup
    difficultyCurve: 'Kurva Kesulitan',
    uiPreferences: 'Preferensi UI',
    blindMode: 'Mode Buta 🔇',
    blindModeDesc: 'Sembunyikan semua transkrip visual & petunjuk',
    uploadedFiles: 'File yang Diunggah',
    invalidDocumentMessage: 'Pilih file PDF, DOCX, DOC, atau TXT yang valid di bawah 10MB.',
    documentUploaded: 'Dokumen diunggah',
    uploadFailed: 'Gagal mengunggah dokumen. Silakan coba lagi.',
    confirmRemove: 'Apakah Anda yakin ingin menghapus',
    failedToRemove: 'Gagal menghapus dokumen.',
    queueLengthError: 'Panjang antrian minimal 1 untuk mode stress test.',
    chaosFeatureRequired: 'Aktifkan setidaknya satu fitur Chaos Engine atau nonaktifkan Chaos Engine.',
    initializationFailed: 'Gagal menginisialisasi sesi. Silakan coba lagi.',
    apiKeysRequired: 'Silakan konfigurasi kunci API Anda di pengaturan sebelum memulai sesi.',
    context: 'Konteks',
    manualInput: 'Manual',
    fromFile: 'Dari File',
    enterContextPlaceholder: 'Masukkan konteks skenario, detail produk, informasi pelanggan, atau latar belakang yang relevan...',
    characters: 'karakter',
    noiseType: 'Jenis Kebisingan',
    office: 'Kantor',
    rain: 'Hujan',
    traffic: 'Lalu Lintas',
    cafe: 'Kafe',
    typeMessage: 'Ketik respons Anda...',
    you: 'Anda',
    speaking: 'Berbicara...',
    listening: 'Mendengarkan...',
    processing: 'Memproses...',
    holdToSpeak: 'Tahan untuk berbicara',
    releaseToSend: 'Lepas untuk mengirim',
    generatingFeedback: 'Menghasilkan umpan balik AI...',
    generatingInsight: 'Menghasilkan wawasan AI...',
  },
  en: {
    // Onboarding
    masterYourVoice: 'Master Your Voice',
    highStakesTraining: 'High-Stakes Communication Training',
    trainForCritical: 'Train for critical conversations with AI-powered simulations that adapt to your performance.',
    ultraLowLatency: 'Ultra-Low Latency',
    naturalConversation: 'Natural Conversation Flow',
    experienceRealistic: 'Experience realistic interactions with voice activity detection and natural interruption capabilities.',
    realWorldDisruptions: 'Real-World Disruptions',
    practiceHandling: 'Practice handling unexpected challenges with background noise, voice variations, and hardware failures.',
    offlineFirst: 'Offline-First',
    trainAnywhere: 'Train Anywhere, Anytime',
    fullFunctionality: 'Full functionality without internet dependency. Your progress stays private and secure on your device.',
    
    // Report
    fillerWordTip: 'Filler word detected. Try pausing silently to gather your thoughts.',
    positiveAspectsDesc: 'Maintained professional tone throughout the conversation.',
    improvementAreasDesc: 'Reduce filler words to improve clarity.',
    nextStepsDesc: 'Practice pausing instead of using filler words.',
    grade: 'Grade',
    notRecorded: 'Not recorded',
    
    // Session
    retrySession: 'Retry This Session',
    sessionStatus: 'Session Status',
    completionStatus: 'Completion Status',
    
    // Quota
    quotaExceeded: 'Quota Exceeded',
    criticalUsage: 'Critical Usage',
    highUsage: 'High Usage',
    normalUsage: 'Normal Usage',
    remainingToday: 'Remaining Today',
    usageTrend: '7-Day Usage Trend (%)',
    
    // Session Setup
    difficultyCurve: 'Difficulty Curve',
    uiPreferences: 'UI Preferences',
    blindMode: 'Blind Mode 🔇',
    blindModeDesc: 'Hide all visual transcripts & cues',
    uploadedFiles: 'Uploaded Files',
    invalidDocumentMessage: 'Please select a valid PDF, DOCX, DOC, or TXT file under 10MB.',
    documentUploaded: 'Document uploaded',
    uploadFailed: 'Failed to upload document. Please try again.',
    confirmRemove: 'Are you sure you want to remove',
    failedToRemove: 'Failed to remove document.',
    queueLengthError: 'Queue length must be at least 1 for stress test mode.',
    chaosFeatureRequired: 'Please enable at least one Chaos Engine feature or disable Chaos Engine.',
    initializationFailed: 'Failed to initialize session. Please try again.',
    apiKeysRequired: 'Please configure your API keys in settings before starting a session.',
    context: 'Context',
    manualInput: 'Manual',
    fromFile: 'From File',
    enterContextPlaceholder: 'Enter scenario context, product details, customer information, or any relevant background...',
    characters: 'characters',
    noiseType: 'Noise Type',
    office: 'Office',
    rain: 'Rain',
    traffic: 'Traffic',
    cafe: 'Cafe',
    typeMessage: 'Type your response...',
    you: 'You',
    speaking: 'Speaking...',
    listening: 'Listening...',
    processing: 'Processing...',
    holdToSpeak: 'Hold to speak',
    releaseToSend: 'Release to send',
    generatingFeedback: 'Generating AI feedback...',
    generatingInsight: 'Generating AI insight...',
  },
};

// Export-specific translations
export const EXPORT_TRANSLATIONS = {
  id: {
    exporting: 'Mengekspor...',
    exportFailed: 'Ekspor Gagal',
    failedToExport: 'Gagal mengekspor laporan',
    noSessionToExport: 'Tidak ada data sesi untuk diekspor',
    selectExportFormat: 'Pilih format ekspor',
    singleMode: 'Mode Tunggal',
    highConfidence: 'Tingkat kepercayaan diri tinggi dipertahankan',
    goodClarity: 'Ucapan jelas dan artikulatif',
    optimalPace: 'Kecepatan bicara optimal',
    minimalFillers: 'Penggunaan kata pengisi minimal',
    improveConfidence: 'Tingkatkan proyeksi kepercayaan diri',
    improveClarity: 'Fokus pada artikulasi yang lebih jelas',
    speedUp: 'Coba bicara sedikit lebih cepat',
    slowDown: 'Pertimbangkan untuk memperlambat tempo',
    reduceFillers: 'Kurangi kata pengisi untuk kejelasan lebih baik',
    playingSegment: 'Memutar segmen',
  },
  en: {
    exporting: 'Exporting...',
    exportFailed: 'Export Failed',
    failedToExport: 'Failed to export report',
    noSessionToExport: 'No session data to export',
    selectExportFormat: 'Select export format',
    singleMode: 'Single Mode',
    highConfidence: 'High confidence level maintained',
    goodClarity: 'Clear and articulate speech',
    optimalPace: 'Optimal speaking pace',
    minimalFillers: 'Minimal use of filler words',
    improveConfidence: 'Work on projecting more confidence',
    improveClarity: 'Focus on clearer articulation',
    speedUp: 'Try to speak a bit faster',
    slowDown: 'Consider slowing down your pace',
    reduceFillers: 'Reduce filler words for better clarity',
    playingSegment: 'Playing segment',
  },
};

// Merge additional translations into main TRANSLATIONS object
Object.keys(ADDITIONAL_TRANSLATIONS).forEach(lang => {
  if (TRANSLATIONS[lang]) {
    Object.assign(TRANSLATIONS[lang], ADDITIONAL_TRANSLATIONS[lang]);
  }
});

// Merge export translations into main TRANSLATIONS object
Object.keys(EXPORT_TRANSLATIONS).forEach(lang => {
  if (TRANSLATIONS[lang]) {
    Object.assign(TRANSLATIONS[lang], EXPORT_TRANSLATIONS[lang]);
  }
});

// Simulation-specific translations
export const SIMULATION_TRANSLATIONS = {
  id: {
    // Blind Mode
    blindModeActive: 'Transkrip visual dan petunjuk disembunyikan. Fokus pada mendengarkan dan berbicara.',
    
    // Chaos Engine
    totalDisruptions: 'Total Gangguan',
    activeDisruptions: 'Gangguan Aktif',
    continuous: 'Berkelanjutan',
    
    // VAD
    vadAutoDetect: 'Otomatis mendeteksi saat Anda berhenti berbicara',
    tapToToggleMic: 'Ketuk untuk toggle mikrofon',
    
    // Session
    settingUpChaos: 'Menyiapkan chaos engine dan sistem audio',
    endSessionConfirm: 'Apakah Anda yakin ingin mengakhiri sesi latihan ini?',
    failedToToggleMic: 'Gagal toggle mikrofon',
    failedToEndSession: 'Gagal mengakhiri sesi dengan benar',
    
    // Noise Types
    office: 'Kantor',
    rain: 'Hujan',
    traffic: 'Lalu Lintas',
    cafe: 'Kafe',
    
    // Disruption Types
    mic_mute: 'Mic Mute',
    connection_drop: 'Koneksi Terputus',
    voice_variation: 'Variasi Suara',
    background_noise: 'Kebisingan Latar',
    hardware_failure: 'Kegagalan Hardware',
    
    // Stress Mode
    missionObjective: 'MISI OBJEKTIF',
    estDuration: 'Est. Durasi',
    completeTest: 'SELESAIKAN TES',
    aiMood: 'MOOD AI',
    difficulty: 'Kesulitan',
    callerIncoming: 'Penelepon berikutnya...',
  },
  en: {
    // Blind Mode
    blindModeActive: 'Visual transcripts and cues are hidden. Focus on listening and speaking.',
    
    // Chaos Engine
    totalDisruptions: 'Total Disruptions',
    activeDisruptions: 'Active Disruptions',
    continuous: 'Continuous',
    
    // VAD
    vadAutoDetect: 'Auto-detects when you stop speaking',
    tapToToggleMic: 'Tap to toggle mic',
    
    // Session
    settingUpChaos: 'Setting up chaos engine and audio systems',
    endSessionConfirm: 'Are you sure you want to end this training session?',
    failedToToggleMic: 'Failed to toggle microphone',
    failedToEndSession: 'Failed to end session properly',
    
    // Noise Types
    office: 'Office',
    rain: 'Rain',
    traffic: 'Traffic',
    cafe: 'Cafe',
    
    // Disruption Types
    mic_mute: 'Mic Mute',
    connection_drop: 'Connection Drop',
    voice_variation: 'Voice Variation',
    background_noise: 'Background Noise',
    hardware_failure: 'Hardware Failure',
    
    // Stress Mode
    missionObjective: 'MISSION OBJECTIVE',
    estDuration: 'Est. Duration',
    completeTest: 'COMPLETE TEST',
    aiMood: 'AI MOOD',
    difficulty: 'Difficulty',
    callerIncoming: 'Next caller incoming...',
  },
};

// Merge simulation translations into main TRANSLATIONS object
Object.keys(SIMULATION_TRANSLATIONS).forEach(lang => {
  if (TRANSLATIONS[lang]) {
    Object.assign(TRANSLATIONS[lang], SIMULATION_TRANSLATIONS[lang]);
  }
});
